export type TerritoryFlag = {
  alt: string
  src: string
}

const FLAGS_BY_KEY: Record<string, TerritoryFlag> = {
  ANDALUCIA: { alt: "Bandera de Andalucía", src: "/ccaa-flags/andalucia.svg" },
  ARAGON: { alt: "Bandera de Aragón", src: "/ccaa-flags/aragon.svg" },
  ASTURIAS: { alt: "Bandera de Asturias", src: "/ccaa-flags/asturias.svg" },
  ILLES_BALEARS: { alt: "Bandera de Illes Balears", src: "/ccaa-flags/illes-balears.svg" },
  CANARIAS: { alt: "Bandera de Canarias", src: "/ccaa-flags/canarias.svg" },
  CANTABRIA: { alt: "Bandera de Cantabria", src: "/ccaa-flags/cantabria.svg" },
  CASTILLA_Y_LEON: { alt: "Bandera de Castilla y León", src: "/ccaa-flags/castilla-y-leon.svg" },
  CASTILLA_LA_MANCHA: { alt: "Bandera de Castilla-La Mancha", src: "/ccaa-flags/castilla-la-mancha.svg" },
  CATALUNYA: { alt: "Bandera de Cataluña", src: "/ccaa-flags/catalunya.svg" },
  EXTREMADURA: { alt: "Bandera de Extremadura", src: "/ccaa-flags/extremadura.svg" },
  GALICIA: { alt: "Bandera de Galicia", src: "/ccaa-flags/galicia.svg" },
  LA_RIOJA: { alt: "Bandera de La Rioja", src: "/ccaa-flags/la-rioja.svg" },
  MADRID: { alt: "Bandera de la Comunidad de Madrid", src: "/ccaa-flags/madrid.svg" },
  MURCIA: { alt: "Bandera de la Región de Murcia", src: "/ccaa-flags/murcia.svg" },
  NAVARRA: { alt: "Bandera de Navarra", src: "/ccaa-flags/navarra.svg" },
  PAIS_VASCO: { alt: "Bandera del País Vasco", src: "/ccaa-flags/pais-vasco.svg" },
  COMUNITAT_VALENCIANA: {
    alt: "Bandera de la Comunitat Valenciana",
    src: "/ccaa-flags/comunitat-valenciana.svg",
  },
  CEUTA: { alt: "Bandera de Ceuta", src: "/ccaa-flags/ceuta.svg" },
  MELILLA: { alt: "Bandera de Melilla", src: "/ccaa-flags/melilla.svg" },
}

const ALIASES: Record<string, keyof typeof FLAGS_BY_KEY> = {
  ANDALUCIA: "ANDALUCIA",
  ALMERIA: "ANDALUCIA",
  CADIZ: "ANDALUCIA",
  CORDOBA: "ANDALUCIA",
  GRANADA: "ANDALUCIA",
  HUELVA: "ANDALUCIA",
  JAEN: "ANDALUCIA",
  MALAGA: "ANDALUCIA",
  SEVILLA: "ANDALUCIA",
  ARAGON: "ARAGON",
  ARAGONESA: "ARAGON",
  ARAGONES: "ARAGON",
  HUESCA: "ARAGON",
  TERUEL: "ARAGON",
  ZARAGOZA: "ARAGON",
  ASTURIAS: "ASTURIAS",
  OVIEDO: "ASTURIAS",
  PRINCIPADO_DE_ASTURIAS: "ASTURIAS",
  BALEAR: "ILLES_BALEARS",
  BALEARES: "ILLES_BALEARS",
  ILLES_BALEARS: "ILLES_BALEARS",
  ISLAS_BALEARES: "ILLES_BALEARS",
  MALLORCA: "ILLES_BALEARS",
  MENORCA: "ILLES_BALEARS",
  CANARIAS: "CANARIAS",
  CANDELARIA: "CANARIAS",
  FUERTEVENTURA: "CANARIAS",
  GRAN_CANARIA: "CANARIAS",
  GRAN_CANARIA_SAU: "CANARIAS",
  EL_HIERRO: "CANARIAS",
  ISLAS_CANARIAS: "CANARIAS",
  LA_GOMERA: "CANARIAS",
  LA_LAGUNA: "CANARIAS",
  LA_PALMA: "CANARIAS",
  LANZAROTE: "CANARIAS",
  LAS_PALMAS: "CANARIAS",
  SANTA_CRUZ_DE_TENERIFE: "CANARIAS",
  TENERIFE: "CANARIAS",
  CANTABRIA: "CANTABRIA",
  AVILA: "CASTILLA_Y_LEON",
  BURGOS: "CASTILLA_Y_LEON",
  CASTILLA_Y_LEON: "CASTILLA_Y_LEON",
  CASTILLA_LEON: "CASTILLA_Y_LEON",
  LEON: "CASTILLA_Y_LEON",
  PALENCIA: "CASTILLA_Y_LEON",
  SALAMANCA: "CASTILLA_Y_LEON",
  SEGOVIA: "CASTILLA_Y_LEON",
  SORIA: "CASTILLA_Y_LEON",
  VALLADOLID: "CASTILLA_Y_LEON",
  ZAMORA: "CASTILLA_Y_LEON",
  ALBACETE: "CASTILLA_LA_MANCHA",
  CASTILLA_LA_MANCHA: "CASTILLA_LA_MANCHA",
  CASTILLA_LA_MANCHA_COMUNIDAD_AUTONOMA: "CASTILLA_LA_MANCHA",
  CIUDAD_REAL: "CASTILLA_LA_MANCHA",
  CUENCA: "CASTILLA_LA_MANCHA",
  GUADALAJARA: "CASTILLA_LA_MANCHA",
  TOLEDO: "CASTILLA_LA_MANCHA",
  BARCELONA: "CATALUNYA",
  CATALUNA: "CATALUNYA",
  CATALUNYA: "CATALUNYA",
  GIRONA: "CATALUNYA",
  LLEIDA: "CATALUNYA",
  TARRAGONA: "CATALUNYA",
  BADAJOZ: "EXTREMADURA",
  CACERES: "EXTREMADURA",
  EXTREMADURA: "EXTREMADURA",
  A_CORUNA: "GALICIA",
  GALICIA: "GALICIA",
  LUGO: "GALICIA",
  OURENSE: "GALICIA",
  PONTEVEDRA: "GALICIA",
  LA_RIOJA: "LA_RIOJA",
  RIOJA: "LA_RIOJA",
  MADRID: "MADRID",
  COMUNIDAD_DE_MADRID: "MADRID",
  MURCIA: "MURCIA",
  REGION_DE_MURCIA: "MURCIA",
  NAVARRA: "NAVARRA",
  COMUNIDAD_FORAL_DE_NAVARRA: "NAVARRA",
  ALAVA: "PAIS_VASCO",
  BIZKAIA: "PAIS_VASCO",
  EUSKADI: "PAIS_VASCO",
  GIPUZKOA: "PAIS_VASCO",
  PAIS_VASCO: "PAIS_VASCO",
  VASCO: "PAIS_VASCO",
  ALICANTE: "COMUNITAT_VALENCIANA",
  ALICANTE_ALACANT: "COMUNITAT_VALENCIANA",
  CASTELLON: "COMUNITAT_VALENCIANA",
  CASTELLON_CASTELLO: "COMUNITAT_VALENCIANA",
  COMUNIDAD_VALENCIANA: "COMUNITAT_VALENCIANA",
  COMUNITAT_VALENCIANA: "COMUNITAT_VALENCIANA",
  VALENCIA: "COMUNITAT_VALENCIANA",
  VALENCIA_VALENCIA: "COMUNITAT_VALENCIANA",
  VALENCIANA: "COMUNITAT_VALENCIANA",
  CEUTA: "CEUTA",
  CIUDAD_AUTONOMA_DE_CEUTA: "CEUTA",
  CIUDAD_AUTONOMA_DE_MELILLA: "MELILLA",
  MELILLA: "MELILLA",
}

export function normalizeTerritoryFlagKey(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase()
}

export function getTerritoryFlag(territoryName: string | null | undefined) {
  if (!territoryName) return null
  const alias = ALIASES[normalizeTerritoryFlagKey(territoryName)]
  return alias ? FLAGS_BY_KEY[alias] : null
}
